
const moves = {
    "sLP": new Move("sLP", 300, []),
    "sLP2": new Move("sLP2", 200, []),
    "sMP": new Move("sMP", 550, []),
    "sHP": new Move("sHP", 1000, []),
    "sLK": new Move("sLK", 400, []),
    "sMK": new Move("sMK", 450, []),
    "sHK": new Move("sHK", 1000, []),
    "cLP": new Move("cLP", 200, []),
    "cMP": new Move("cMP", 600, []),
    "cHP": new Move("cHP", 900, []),
    "cLK": new Move("cLK", 200, []),
    "cMK": new Move("cMK", 150, []),
    "cMK2": new Move("cMK2", 150, []),
    "cMK3": new Move("cMK3", 200, []),
    "cMK4": new Move("cMK4", 250, []),
    "cMK5": new Move("cMK5", 400, []),
    "cHK": new Move("cHK", 1100, []),
    "jLP": new Move("jLP", 250, []),
    "jMP": new Move("jMP", 150, []),
    "jMP2": new Move("jMP2", 150, []),
    "jMP3": new Move("jMP3", 150, []),
    "jMP4": new Move("jMP4", 150, []),
    "jMP5": new Move("jMP5", 150, []),
    "jMP6": new Move("jMP6", 250, []),
    "jHP": new Move("jHP", 900, []),
    "jLK": new Move("jLK", 250, []),
    "jMK": new Move("jMK", 200, []),
    "jMK2": new Move("jMK2", 350, []),
    "jHK": new Move("jHK", 900, []),
    "Ringlet": new Move("Ringlet Spike", 600, ["isProjectile", "is50%DamageScaling"]),
    "Updo (L)": new Move("Updo (L)", 800, []),
    "Updo (M)": new Move("Updo (M)", 600, []),
    "Updo (M)2": new Move("Updo (M)2", 400, []),
    "Updo (H)": new Move("Updo (H)", 900, []),
    "Updo (H)2": new Move("Updo (H)2", 300, []),
    "Updo (H)3": new Move("Updo (H)3", 300, []),
    "Hairball (L)": new Move("Hairball (L)", 300, []),
    "Hairball (L)2": new Move("Hairball (L)2", 300, []),
    "Hairball (L)3": new Move("Hairball (L)3", 400, []),
    "Hairball (M)": new Move("Hairball (M)", 300, []),
    "Hairball (M)2": new Move("Hairball (M)2", 300, []),
    "Hairball (M)3": new Move("Hairball (M)3", 300, []),
    "Hairball (M)4": new Move("Hairball (M)4", 400, []),
    "Hairball (H)": new Move("Hairball (H)", 300, []),
    "Hairball (H)2": new Move("Hairball (H)2", 300, []),
    "Hairball (H)3": new Move("Hairball (H)3", 300, []),
    "Hairball (H)4": new Move("Hairball (H)4", 300, []),
    "Hairball (H)5": new Move("Hairball (H)5", 300, []),
    "Hairball (H)6": new Move("Hairball (H)6", 400, []),
    "Airball": new Move("Airball", 300, []),
    "Airball2": new Move("Airball2", 300, []),
    "Airball3": new Move("Airball3", 300, []),
    "Airball4": new Move("Airball4", 400, []),
    "Throw": new Move("Throw", 0, ["isGrab"]),
    "Throw2": new Move("Throw2", 212, ["isGrab"]),
    "Throw3": new Move("Throw3", 212, ["isGrab"]),
    "Throw4": new Move("Throw4", 212, ["isGrab"]),
    "Throw5": new Move("Throw5", 212, ["isGrab", "is50%DamageScaling"]),
    "Air Throw": new Move("Air Throw", 300, ["isGrab"]),
    "Air Throw2": new Move("Air Throw2", 1000, ["isGrab", "is50%DamageScaling"]),
    "Tag": new Move("Tag", 500, ["isTag"]),
    "Snapback": new Move("Snapback", 0, ["isSnapback"]),
    "Fenrir Drive": new Move("Fenrir Drive", 400, []),
    "Fenrir Drive2": new Move("Fenrir Drive2", 200, ["isHitGrab"]),
    "Fenrir Drive3": new Move("Fenrir Drive3", 200, ["isHitGrab"]),
    "Fenrir Drive4": new Move("Fenrir Drive4", 400, ["isHitGrab"]),
    "Fenrir Drive5": new Move("Fenrir Drive5", 1500, ["isHitGrab"]),
    "Fenrir Drive6": new Move("Fenrir Drive6", 200, ["isHitGrab"]),
    "Gregor Samson": new Move("Gregor Samson", 300, []),
    "Gregor Samson2": new Move("Gregor Samson2", 300, []),
    "Gregor Samson3": new Move("Gregor Samson3", 300, []),
    "Gregor Samson4": new Move("Gregor Samson4", 300, []),
    "Gregor Samson5": new Move("Gregor Samson5", 1750, []),
    "Air Gregor Samson": new Move("Gregor Samson", 250, []),
    "Air Gregor Samson2": new Move("Gregor Samson2", 250, []),
    "Air Gregor Samson3": new Move("Gregor Samson3", 250, []),
    "Air Gregor Samson4": new Move("Gregor Samson4", 250, []),
    "Air Gregor Samson5": new Move("Gregor Samson5", 1250, []),
    "Trichobezoar (first frame)": new Move("Trichobezoar (first frame)", 4750, []),
    "Trichobezoar": new Move("Trichobezoar", 3000, []),
    "Born With It": new Move("Born With It", 5, ["isProjectile", "is45%MinimumScaling"]),
};

const filia = new Character("Filia", moves);
