
const moves = {
    "sLP": new Move("sLP", 300, false),
    "sLP2": new Move("sLP2", 200, false),
    "sMP": new Move("sMP", 550, false),
    "sHP": new Move("sHP", 1000, false),
    "sLK": new Move("sLK", 400, false),
    "sMK": new Move("sMK", 450, false),
    "sHK": new Move("sHK", 1000, false),
    "cLP": new Move("cLP", 200, false),
    "cMP": new Move("cMP", 600, false),
    "cHP": new Move("cHP", 900, false),
    "cLK": new Move("cLK", 200, false),
    "cMK": new Move("cMK", 150, false),
    "cMK2": new Move("cMK2", 150, false),
    "cMK3": new Move("cMK3", 200, false),
    "cMK4": new Move("cMK4", 250, false),
    "cMK5": new Move("cMK5", 400, false),
    "cHK": new Move("cHK", 1100, false),
    "jLP": new Move("jLP", 250, false),
    "jMP": new Move("jMP", 150, false),
    "jMP2": new Move("jMP2", 150, false),
    "jMP3": new Move("jMP3", 150, false),
    "jMP4": new Move("jMP4", 150, false),
    "jMP5": new Move("jMP5", 150, false),
    "jMP6": new Move("jMP6", 250, false),
    "jHP": new Move("jHP", 900, false),
    "jLK": new Move("jLK", 250, false),
    "jMK": new Move("jMK", 200, false),
    "jMK2": new Move("jMK2", 350, false),
    "jHK": new Move("jHK", 900, false),
    "Ringlet Spike": new Move("Ringlet Spike", 600, false),
    "Updo (L)": new Move("Updo (L)", 800, false),
    "Updo (M)": new Move("Updo (M)", 600, false),
    "Updo (M)2": new Move("Updo (M)2", 400, false),
    "Updo (H)": new Move("Updo (H)", 900, false),
    "Updo (H)2": new Move("Updo (H)2", 300, false),
    "Updo (H)3": new Move("Updo (H)3", 300, false),
    "Hairball (L)": new Move("Hairball (L)", 300, false),
    "Hairball (L)2": new Move("Hairball (L)2", 300, false),
    "Hairball (L)3": new Move("Hairball (L)3", 400, false),
    "Hairball (M)": new Move("Hairball (M)", 300, false),
    "Hairball (M)2": new Move("Hairball (M)2", 300, false),
    "Hairball (M)3": new Move("Hairball (M)3", 300, false),
    "Hairball (M)4": new Move("Hairball (M)4", 400, false),
    "Hairball (H)": new Move("Hairball (H)", 300, false),
    "Hairball (H)2": new Move("Hairball (H)2", 300, false),
    "Hairball (H)3": new Move("Hairball (H)3", 300, false),
    "Hairball (H)4": new Move("Hairball (H)4", 300, false),
    "Hairball (H)5": new Move("Hairball (H)5", 300, false),
    "Hairball (H)6": new Move("Hairball (H)6", 400, false),
    "Airball": new Move("Airball", 300, false),
    "Airball2": new Move("Airball2", 300, false),
    "Airball3": new Move("Airball3", 300, false),
    "Airball4": new Move("Airball4", 400, false),
};

const filia = new Character("Filia", moves);
